### ISSUE TITLE
使用过程中发现的问题

### ISSUE THREAD

**Issue by ruijun** [maning0303/GankMM#1]
**问题**
- 点击设置--意见反馈--出现闪退
- 收藏，分类浏览界面的ViewPager滑动会出现透明的间距

**手机系统信息**
- 型号：OPPOR7sm
- ColorOS版本：V2.1
- Android版本：5.1.1

**Comment by maning0303** [comment]
请问是最新版的吗？麻烦你把崩溃日志贴出来看看---目录：/GankMM/CrashLog 。

**Comment by ruijun** [comment]
@maning0303 

``` java
App Version: 1.2.4_7
OS Version: 5.1.1_22
Vendor: OPPO
Model: OPPO R7sm
CPU ABI: armeabi-v7a

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.maning.gankmm/com.umeng.fb.ConversationActivity}: java.lang.IllegalArgumentException: ResClass is not initialized. Please make sure you have added necessary resources. Also make sure you have com.maning.gankmm.R$* configured in obfuscation. field=umeng_fb_activity_conversation
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2504)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2576)
    at android.app.ActivityThread.access$1000(ActivityThread.java:163)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1461)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:159)
    at android.app.ActivityThread.main(ActivityThread.java:5541)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:975)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
Caused by: java.lang.IllegalArgumentException: ResClass is not initialized. Please make sure you have added necessary resources. Also make sure you have com.maning.gankmm.R$* configured in obfuscation. field=umeng_fb_activity_conversation
    at com.umeng.fb.util.Res.a(Unknown Source)
    at com.umeng.fb.util.Res.d(Unknown Source)
    at com.umeng.fb.res.f.a(Unknown Source)
    at com.umeng.fb.ConversationActivity.onCreate(Unknown Source)
    at android.app.Activity.performCreate(Activity.java:6163)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2457)
    ... 10 more
```

**Comment by maning0303** [comment]
Umeng论坛有这个问题：[http://bbs.umeng.com/thread-8071-1-1.html](http://bbs.umeng.com/thread-8071-1-1.html)
我在我的手机和模拟器上没发现这个问题，你加一下我的QQ：154292322

**Comment by maning0303** [comment]
你可以把源码跑一下，把libraryumeng这个library的manifest文件的包名改一下package="com.maning.gankmm"，试试这个方式可不可以！

**Comment by ruijun** [comment]
build源码编出的apk是没有这个问题的。但是从[fir.im](http://fir.im/gankmm)下载的apk就有这个问题。

**Comment by ruijun** [comment]
@maning0303  我提交了个PR

**Comment by maning0303** [comment]
@ruijun 代码我已经合并了 ，感谢提交代码，你那边加了这句话打包没有问题了吧！

**Comment by ruijun** [comment]
@maning0303 没有问题，我测试过packageName与applicationId不一致的情况了

**Comment by maning0303** [comment]
@ruijun 赞
