### ISSUE TITLE
4.4版本启动出现程序崩溃

### ISSUE THREAD

**Issue by 2605072201** [maning0303/GankMM#3]
报空指针异常

**Comment by maning0303** [comment]
请问能不能找到crash日志文件发过来看看。

**Comment by jessos** [comment]
我的情况跟你是一样的
闪屏页之后就闪退
手机是红米2，Android 4.4

错误日志：
```
Caused by: java.lang.NullPointerException
at com.maning.gankmm.utils.StatusBarUtil.setRootView(StatusBarUtil.java:416)
at com.maning.gankmm.utils.StatusBarUtil.setColor(StatusBarUtil.java:56)
at com.maning.gankmm.ui.base.BaseActivity.initStatus(BaseActivity.java:40)
at com.maning.gankmm.ui.base.BaseActivity.onCreate(BaseActivity.java:30)
at com.maning.gankmm.ui.activity.SplashAdActivity.onCreate(SplashAdActivity.java:35)
```

**Comment by jessos** [comment]
```java
ViewGroup rootView = (ViewGroup) ((ViewGroup) activity.findViewById(android.R.id.content)).getChildAt(0);
rootView.setFitsSystemWindows(true);
rootView.setClipToPadding(true);
```
rootView is null

把
`ViewGroup rootView = (ViewGroup) ((ViewGroup) activity.findViewById(android.R.id.content)).getChildAt(0);` 
修改成
`ViewGroup rootView = (ViewGroup) activity.getWindow().getDecorView();`
就好了

**Comment by maning0303** [comment]
好的，谢谢您的反馈，我也在一个手机发现了这个问题。我会在下一版本改了！
